### ISSUE TITLE
[FR] Order of pictures

### ISSUE THREAD

**Issue by jagjordi** [giejay/Immich-Android-TV#11]
Now it seems the pictures are always shown starting from the newest one,

Would it be possible to have the option of sorting them in the other direction?

**Comment by giejay** [comment]
Yes, I can add that in a next release, together with Album sorting.

**Comment by giejay** [comment]
I just pushed update 1.23 to the play store which contains the following sorting options:
Album: Alphabetically or Last Updated
Photos: Newest - Oldest, Oldest - Newest or Alphabetically (name of item). 

Both sorting options also have a "reverse" option. To for example show it from Z-A instead of A-Z

**Comment by madkatz01** [comment]
This is great! Thanks for the quick update!

**Comment by Philshappy** [comment]
Wow, those are great improvements. Love this app. I new issue surfaced so I will open a new issue.
