### ISSUE TITLE
[FR] Fit image into frame

### ISSUE THREAD

**Issue by TheZoker** [giejay/Immich-Android-TV#75]
**Is your feature request related to a problem? Please describe.**
I often have the issue, that my images have a black block on the top and bottom of the image since the ratio is not the same as the TV. It would be nice to have an option to fit images into the displayed frame size. Thanks!

**Describe the solution you'd like**
Option to allow image to fit to frame. 

**Additional context**

**Comment by giejay** [comment]
But that distorts the image or it cuts out part right?

**Comment by TheZoker** [comment]
Yes that would cut the image. But I prefer to cut some small pieces of the image instead of the black bars on top and bottom

**Comment by giejay** [comment]
Fixed with: https://github.com/giejay/Immich-Android-TV/releases/tag/2.3.0

You can now find a couple of new settings in "View":

<img width="404" alt="image" src="https://github.com/user-attachments/assets/b55a7fde-8092-4f64-8c0e-3cbd9d814c51" />

Safe center crop allows you specify a maximum loss of image, either in width or in height (or both)
